### ISSUE TITLE
Label creation failure on 2nd address line:1e etage

### ISSUE THREAD

**Issue by bamboekeizer** [myparcelnl/magento#264]
A customer created an address with regular street address and number, but added the wording "1e etage" on the second address line. When attempting to create a label in the backend, the items are marked as shipped but the creation of the label fails.
Here is the exception dump (anonomised):
[2019-04-22 09:53:44] main.CRITICAL: Error in MyParcel API request: 0 - data.shipments[0].recipient.street NULL value found, but a string is required - Failed validation against JSON-SCHEMA shipment/post_shipments_request.json Url: https://api.myparcel.nl/shipments Request: {"data":{"shipments":[{"recipient":{"cc":"NL","person":"frodo shire","postal_code":"2226 KL","city":"Shire","email":"frodoshire@gmail.com","phone":"","street":null,"street_additional_info":"","number":null,"number_suffix":""},"options":{"package_type":1,"label_description":"2000019284","only_recipient":0,"signature":0,"return":0,"delivery_type":2,"large_format":0},"carrier":1,"reference_identifier":"162"}]}} {"exception":"[object] (Exception(code: 0): Error in MyParcel API request: 0 - data.shipments[0].recipient.street NULL value found, but a string is required - Failed validation against JSON-SCHEMA shipment/post_shipments_request.json Url: https://api.myparcel.nl/shipments Request: {\"data\":{\"shipments\":[{\"recipient\":{\"cc\":\"NL\",\"person\":\"frodo shire\",\"postal_code\":\"2226 KL\",\"city\":\"Shire\",\"email\":\"frodoshire@gmail.com\",\"phone\":\"\",\"street\":null,\"street_additional_info\":\"\",\"number\":null,\"number_suffix\":\"\"},\"options\":{\"package_type\":1,\"label_description\":\"2000019284\",\"only_recipient\":0,\"signature\":0,\"return\":0,\"delivery_type\":2,\"large_format\":0},\"carrier\":1,\"reference_identifier\":\"162\"}]}} at /vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php:140)"} []

From system.log:
[2019-04-22 09:53:44] main.CRITICAL: An error has occurred while validating the address: Landweg 99 1e etage. Check number and number suffix.-Exception: Invalid full street supplied: Landweg 99 1e etage in /vendor/myparcelnl/sdk/src/Helper/SplitStreet.php:112 Stack trace: #0 /vendor/myparcelnl/sdk/src/Helper/SplitStreet.php(52): MyParcelNL\Sdk\src\Helper\SplitStreet::validate('Landweg 99 1e e...', 0, Array) #1 /vendor/myparcelnl/sdk/src/Model/MyParcelConsignment.php(701): MyParcelNL\Sdk\src\Helper\SplitStreet::splitStreet('Landweg 99 1e e...') #2 /vendor/myparcelnl/magento/Model/Sales/MyParcelTrackTrace.php(147): MyParcelNL\Sdk\src\Model\MyParcelConsignment->setFullStreet('Landweg 99\n1e e...') #3 /vendor/myparcelnl/magento/Observer/NewShipment.php(93):

**Comment by adem-demir** [comment]
Tested in latest version. The API doesn't accept more than 4 chars in the second line as additional street (suffix). See below screenshot with correct error example:

![image](https://user-images.githubusercontent.com/37372250/68208302-2c6b7b80-ffd1-11e9-8bb2-9355e775fb6e.png)
