### ISSUE TITLE
Cron job: myparcel_update_status fails on PHP error 

### ISSUE THREAD

**Issue by duckchip** [myparcelnl/magento#474]
**Describe the bug**
When running the cronjob, myparcel_update_status we receive an error:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to MyParcelNL\Sdk\src\Model\MyParcelRequest::setRequestParameters() must be of the type string, null given, called in /Volumes/Projects/magento2/project/vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php on line 360 and defined in /Volumes/Projects/magento2/project/vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php:112
Stack trace:
#0 /Volumes/Projects/magento2/project/vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php(360): MyParcelNL\Sdk\src\Model\MyParcelRequest->setRequestParameters(NULL, NULL, 'Accept: applica...')
#1 /Volumes/Projects/magento2/project/vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php(254): MyParcelNL\Sdk\src\Helper\MyParcelCollection->setLatestData()
#2 /Volumes/Projects/magento2/project/vendor/myparcelnl/magento/Cron/UpdateStatus.php(67): MyParcelNL\Magento\Model\Sales\MagentoOrderCollection->setLatestData()
#3 [internal function]: MyParcelNL\Magento\Cron\UpdateStatus->execute(Object(Magento\Cron\Model\ in /Volumes/Projects/magento2/project/vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php on line 112

Fatal error: Uncaught TypeError: Argument 1 passed to MyParcelNL\Sdk\src\Model\MyParcelRequest::setRequestParameters() must be of the type string, null given, called in /Volumes/Projects/magento2/project/vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php on line 360 and defined in /Volumes/Projects/magento2/project/vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php:112
Stack trace:
#0 /Volumes/Projects/magento2/project/vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php(360): MyParcelNL\Sdk\src\Model\MyParcelRequest->setRequestParameters(NULL, NULL, 'Accept: applica...')
#1 /Volumes/Projects/magento2/project/vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php(254): MyParcelNL\Sdk\src\Helper\MyParcelCollection->setLatestData()
#2 /Volumes/Projects/magento2/project/vendor/myparcelnl/magento/Cron/UpdateStatus.php(67): MyParcelNL\Magento\Model\Sales\MagentoOrderCollection->setLatestData()
#3 [internal function]: MyParcelNL\Magento\Cron\UpdateStatus->execute(Object(Magento\Cron\Model\ in /Volumes/Projects/magento2/project/vendor/myparcelnl/sdk/src/Model/MyParcelRequest.php on line 112
```

**To Reproduce**
1. Magento 2.3.5
2. magento/myparcelnl v4.1.1 (also happens on 3.3.0)
3. myparcelnl/sdk v v5.2.0 (also happens on v3.1.7)
4. run cron job (using bin/magento cron:run or magerun: `tools/n98-magerun2.phar sys:cron:run myparcel_update_status`
**Expected behavior**
Cron job runs without errors. 

**Additional context**
A noticed a very odd logic is used to fetch the api key from the consignments, which in this case is NULL, resulting in the code to crash. Passing by reference seems dangerous..

**Comment by duckchip** [comment]
#328 
#408

**Comment by Kroellie** [comment]
+1

**Comment by Quazz** [comment]
Any news on this? 

It seems like the key never gets retrieved in the cron task.

**Comment by RichardPerdaan** [comment]
I have tested this issue with the latest version of the MyParcel plugin and the problem seems to be solved. If the problem is still there, we can always reopen the issue.
