### ISSUE TITLE
Street validation for Belgium address fails

### ISSUE THREAD

**Issue by rikwillems** [myparcelnl/magento#505]
When I try to checkout with an address in Belgium I get the error below. When I reset the `getStreetRegexByCountry` function to a previous one it works again.

```
"Fatal Error: 'Uncaught TypeError: preg_match() expects parameter 1 to be string, null given in \/vendor\/myparcelnl\/sdk\/src\/Helper\/ValidateStreet.php:39\nStack trace:\n#0 \/vendor\/myparcelnl\/sdk\/src\/Helper\/ValidateStreet.php(39): preg_match(NULL, 'Voorschoterlaan...', NULL)\n#1 \/vendor\/myparcelnl\/magento\/Model\/Quote\/SaveOrderBeforeSalesModelQuoteObserver.php(92): MyParcelNL\\Sdk\\src\\Helper\\ValidateStreet::validate('Voorschoterlaan...', 'NL', 'BE')\n#2 \/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(88): MyParcelNL\\Magento\\Model\\Quote\\SaveOrderBeforeSalesModelQuoteObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#3 \/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(74): Magento\\Framework\\Event\\Invo' in '\/vendor\/myparcelnl\/sdk\/src\/Helper\/ValidateStreet.php' on line 39"```

**Comment by AlexNauta** [comment]
https://github.com/myparcelnl/magento/issues/504

**Comment by RichardPerdaan** [comment]
I have tested this issue with the latest version of the MyParcel plugin and the problem seems to be solved. If the problem is still there, we can always reopen the issue.
