### ISSUE TITLE
API key is not good. To get your personal API credentials you should contact MyParcel.

### ISSUE THREAD

**Issue by bezigeboefjes** [myparcelnl/magento#52]
Ik heb onlangs onze shop omgebouwd naar een Multistore (meerdere shops, maar ook meerdere talen). Nu krijg ik sinds deze omzetting de volgende foutmelding bij het genereren van een label:
---
API key is not good. To get your personal API credentials you should contact MyParcel.
---
Ik heb al een keer de API key vernieuwd en de API key per store ingevoerd, helaas allemaal zonder resultaat. Ik heb meerdere omgevingen (dev, test, prod). Alle omgevingen geven dezelfde melding. Voor de aanpassing werkte MyParcel nog prima.

**Steps to reproduce:**

- Stores -> All stores
- Create Store
- Create Store View

![image](https://user-images.githubusercontent.com/20379631/28241805-ddaef2ba-699b-11e7-9780-a804c225faba.png)

**Comment by bezigeboefjes** [comment]
In exception.log:

```
[2017-07-15 18:32:22] main.CRITICAL: Exception: Warning: implode(): Invalid arguments passed in /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php on line 257 in /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'implode(): Inva...', '/var/www/vhosts...', 257, Array)
#1 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/myparcelnl/sdk/src/Helper/MyParcelCollection.php(257): implode(';', NULL)
#2 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/myparcelnl/magento/Model/Sales/MagentoOrderCollection.php(342): MyParcelNL\Sdk\src\Helper\MyParcelCollection->setLatestData()
#3 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(89): MyParcelNL\Magento\Model\Sales\MagentoOrderCollection->createMyParcelConcepts()
#4 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/myparcelnl/magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php(59): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->massAction()
#5 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/var/generation/MyParcelNL/Magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack/Interceptor.php(24): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack->execute()
#6 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/App/Action/Action.php(102): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->execute()
#7 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/var/generation/MyParcelNL/Magento/Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack/Interceptor.php(39): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->___callPlugins('dispatch', Array, Array)
#9 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/App/FrontController.php(55): MyParcelNL\Magento\Controller\Adminhtml\Order\CreateAndPrintMyParcelTrack\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#12 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#13 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#16 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#18 /var/www/vhosts/bezigeboefjes.nl/test.bezigeboefjes.nl/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#19 {main} [] []
```

**Comment by reindert-vetter** [comment]
Hier gaat inderdaad iets mis. Gaat dit ook fout bij nieuwe orders? 

Zou je mij een mail kunnen sturen met jouw gegevens? Dan kan ik met je meekijken of via ssh het probleem oplossen.

**Comment by bezigeboefjes** [comment]
Net getest met een nieuwe order in de test omgeving, de foutmelding blijft. Ik heb je een mail gestuurd.
