### ISSUE TITLE
Checkout shipping methods keep loading when inapplicable method shown for disabled country

### ISSUE THREAD

**Issue by unlocdavid** [myparcelnl/magento#870]
### Plugin version

4.17.0

### Magento version

2.4.7-p3

### PHP version

8.2

### What went wrong?

The sipping methods in the checkout keeps loading when there is a shipping method active that is disabled for a country and the option 'Show Method if Not Applicable' is set to true.

### Reproduction steps

1. Enable a shipping method like Free shipping and limit it to a certain country. Make sure the option 'Show Method if Not Applicable' is set to true.
2. Go to the checkout and use an address with a different country than the country restricted shipping method.
3. Observe the loading spinner keeps spinning.

### Relevant log output

```shell
// Browser console:

checkout.js:155 Uncaught TypeError: Cannot read properties of null (reading 'indexOf')
    at checkout.js:155:39
    at Array.find (<anonymous>)
    at Object.findOriginalRateByCarrierCode (checkout.js:154:28)
    at checkout.js:279:22
    at Array.filter (<anonymous>)
    at updateAllowedShippingMethods (checkout.js:278:64)
    at ko.subscription._callback (checkout.js:95:9)
    at Function.notifySubscribers (knockout.js:1401:50)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout.js:2310:68)
    at Function.evaluateImmediate (knockout.js:2253:40)
```

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!
This is what I've done:
The issue appears to be caused by the shipping method selection process in the checkout. We'll modify the `onShippingMethodUpdate` function in the `view/frontend/web/js/view/delivery-options.js` file to handle cases where the shipping method is not available or not a MyParcel method. This should prevent the infinite loading spinner.

I also created pull request: https://github.com/myparcelnl/magento/pull/871

---
This bug was fixed for free by Latta AI - https://latta.ai
